#!/bin/sh
set -x

Install_Puppet () {
   echo INSTALL PUPPET
   sudo wget https://apt.puppetlabs.com/puppetlabs-release-trusty.deb
   sudo dpkg --force-all -i puppetlabs-release-trusty.deb
   sudo apt-get -f -y install  puppetmaster
   sudo apt-get -f -y install  puppet
}

sudo apt update && sudo apt upgrade

sudo apt install curl

sudo apt update

sudo apt install default-jre

sudo apt -y install dpkg

sudo dpkg -i apt.deb

sudo apt-get -f -y install  openjdk-8-jre-headless

Install_Puppet

puppet apply manifests/site.pp

ls -l /tmp/HelloWorld

cat /tmp/HelloWorld

